### ISSUE TITLE
Implicit Telescope dependency - necessary?

### ISSUE THREAD

**Issue by weilbith** [IndianBoy42/hop-extensions#2]
Hey, I had issues setting up this plugin because it was not listing the dependency to Telescope. Is that necessary? Seems unrelated. Maybe it would be amazing to only require telescope on demand. 😃

**Comment by IndianBoy42** [comment]
Oh, yeah sorry. 

It technically shouldn't be necessary, I just used a helper function inside telescope that returns the LSP diagnostics in a nicely structured array.

This was fine when this was just a part of my nvim config but i forgot about it when extracting.

I can try fix it later, don't have much time for nvim stuff nowadays though

**Comment by weilbith** [comment]
The diagnostics don't work for me... So maybe it is broken anyway? 🤔 

No problem. I have Telescope in my setup and I can lazy load it here. It works right now.
